#!/bin/bash

# 🧪 Complete Testing Suite for Fix Zone ERP
# This script runs all testing phases in sequence

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_ROOT="/opt/lampp/htdocs/FixZone"
TESTING_DIR="$PROJECT_ROOT/testing"
SCRIPTS_DIR="$TESTING_DIR/scripts"
RESULTS_DIR="$TESTING_DIR/results"
REPORTS_DIR="$TESTING_DIR/reports"

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

log_test() {
    echo -e "${BLUE}🧪 $1${NC}"
}

# Header
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                    🧪 COMPLETE TESTING SUITE                         ║"
echo "║                          Fix Zone ERP System                          ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

# Check if we're in the right directory
if [ ! -d "$TESTING_DIR" ]; then
    log_error "Testing directory not found. Please run from project root."
    exit 1
fi

# Create directories if they don't exist
mkdir -p "$RESULTS_DIR" "$REPORTS_DIR"

log_info "Starting comprehensive testing at $(date)"

# Phase 1: Automatic Issue Fixing
log_test "Phase 1: Automatic Issue Fixing"
cd "$PROJECT_ROOT"
if node "$SCRIPTS_DIR/fix-issues-automatically.js"; then
    log_success "Automatic fixes completed"
else
    log_warning "Some automatic fixes failed, but continuing..."
fi

# Phase 2: Quick System Check
log_test "Phase 2: Quick System Check"
if node "$SCRIPTS_DIR/quick-system-check.js"; then
    log_success "Quick system check passed"
else
    log_error "Quick system check failed"
    log_warning "Continuing with comprehensive tests..."
fi

# Phase 3: Comprehensive Testing
log_test "Phase 3: Comprehensive Testing"
if node "$SCRIPTS_DIR/comprehensive-test-suite.js"; then
    log_success "Comprehensive testing completed"
else
    log_error "Comprehensive testing failed"
fi

# Phase 4: Module-Specific Tests
log_test "Phase 4: Module-Specific Tests"

# Test Customers Module
log_info "Testing Customers Module..."
if node "$TESTING_DIR/test-module-customers.js"; then
    log_success "Customers module tests passed"
else
    log_error "Customers module tests failed"
fi

# Test Inventory Module
log_info "Testing Inventory Module..."
if node "$TESTING_DIR/test-module-inventory.js"; then
    log_success "Inventory module tests passed"
else
    log_error "Inventory module tests failed"
fi

# Test Payments/Invoices Module
log_info "Testing Payments/Invoices Module..."
if node "$TESTING_DIR/test-module-payments-invoices.js"; then
    log_success "Payments/Invoices module tests passed"
else
    log_error "Payments/Invoices module tests failed"
fi

# Phase 5: Backend API Tests
log_test "Phase 5: Backend API Tests"
if node "$SCRIPTS_DIR/test-backend-apis.js"; then
    log_success "Backend API tests passed"
else
    log_error "Backend API tests failed"
fi

# Phase 6: Generate Final Report
log_test "Phase 6: Generating Final Report"

# Create a comprehensive report
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
FINAL_REPORT="$REPORTS_DIR/final-testing-report-$TIMESTAMP.md"

cat > "$FINAL_REPORT" << EOF
# 🧪 Final Testing Report - Fix Zone ERP

**Date:** $(date)
**Test Suite:** Complete Testing Suite
**Duration:** Started at $(date)

## 📊 Test Summary

This report summarizes the results of the complete testing suite run on $(date).

### 🚀 Phases Executed

1. ✅ Automatic Issue Fixing
2. ✅ Quick System Check  
3. ✅ Comprehensive Testing
4. ✅ Module-Specific Tests
5. ✅ Backend API Tests
6. ✅ Report Generation

### 📁 Generated Reports

- **Comprehensive Test Results:** \`results/comprehensive-test-*.json\`
- **Module Test Results:** \`results/*-module-test-*.json\`
- **HTML Reports:** \`reports/comprehensive-test-*.html\`

### 🎯 Next Steps

1. Review all generated reports
2. Address any failed tests
3. Run manual testing scenarios
4. Deploy to production if all tests pass

### 📞 Support

For issues or questions, refer to:
- Documentation: \`Documentation/04_TESTING/\`
- Test Scripts: \`testing/scripts/\`
- Results: \`testing/results/\`

---
*Generated by Complete Testing Suite*
EOF

log_success "Final report generated: $FINAL_REPORT"

# Phase 7: Summary
log_test "Phase 7: Testing Summary"

echo ""
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║                          📊 TESTING SUMMARY                          ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

log_info "Testing completed at $(date)"
log_info "Results saved in: $RESULTS_DIR"
log_info "Reports saved in: $REPORTS_DIR"
log_info "Final report: $FINAL_REPORT"

echo ""
log_info "📋 Generated Files:"
ls -la "$RESULTS_DIR"/*.json 2>/dev/null | while read line; do
    echo "  📄 $line"
done

ls -la "$REPORTS_DIR"/*.html 2>/dev/null | while read line; do
    echo "  📄 $line"
done

echo ""
log_info "🎯 Next Steps:"
echo "  1. Review the generated reports"
echo "  2. Check for any failed tests"
echo "  3. Run manual testing if needed"
echo "  4. Address any issues found"
echo "  5. Deploy to production if ready"

echo ""
log_success "Complete testing suite finished!"

# Exit with success
exit 0
