USE FZ;
CREATE TABLE IF NOT EXISTS SparePartRequest (
  id INT AUTO_INCREMENT PRIMARY KEY,
  repairRequestId INT NOT NULL,
  partName VARCHAR(255) NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  status ENUM('PENDING','APPROVED','REJECTED','ORDERED','RECEIVED') DEFAULT 'PENDING',
  requestedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  requestedById INT NOT NULL,
  notes TEXT NULL,
  expectedPrice DECIMAL(10,2) NULL,
  approvedById INT NULL,
  approvedAt DATETIME NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_spr_repair FOREIGN KEY (repairRequestId) REFERENCES RepairRequest(id),
  CONSTRAINT fk_spr_user FOREIGN KEY (requestedById) REFERENCES User(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
