USE FZ;
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'FZ' 
  AND TABLE_NAME = 'RepairRequest'
  AND COLUMN_NAME IN ('estimatedCost', 'estimatedCostMin', 'estimatedCostMax')
ORDER BY ORDINAL_POSITION;
